name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        check:
          - format
    name: Check ${{ matrix.check }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install
        run: pnpm install --ignore-scripts

      - name: Check
        run: pnpm check:${{ matrix.check }}

  # Build all packages and applications, and creates Docker images
  build-latest:
    name: build
    needs: [check]
    uses: ./.github/workflows/build-and-dockerize.yaml
    # Only run for `main` branch
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    with:
      imageTag: ${{ github.sha }}
      publishLatest: true
      targets: "build"
      publishPrComment: false
    secrets: inherit

  # Deploy to preview environment
  deploy-preview:
    name: deploy
    needs: [build-latest]
    uses: ./.github/workflows/deploy.yaml
    concurrency:
      group: "deploy-dev"
    # Only run for `main` branch
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    with:
      ref: ${{ github.sha }}
      environment: "theguild/dev"
    secrets: inherit

  deploy-ui:
    name: Deploy UI
    runs-on: ubuntu-latest
    needs: [check]
    if:
      github.event.pull_request.head.repo.full_name == github.repository || github.event_name ==
      'push'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install
        run: pnpm install --ignore-scripts

      - uses: the-guild-org/shared-config/website-cf@main
        name: Deploy
        with:
          cloudflareApiToken: ${{ secrets.GUILD_CLOUDFLARE_API_TOKEN }}
          cloudflareAccountId: ${{ secrets.GUILD_CLOUDFLARE_ACCOUNT_ID }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          projectName: graphwebhooks
          prId: ${{ github.event.pull_request.number }}
          websiteDirectory: web
          buildScript: pnpm build
          artifactDir: dist

  deploy-management-api:
    name: Deploy Management API
    runs-on: ubuntu-latest
    needs: [check]
    # Only run for `main` branch
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install
        run: pnpm install --ignore-scripts

      - uses: cloudflare/wrangler-action@v3
        name: Deploy
        with:
          apiToken: ${{ secrets.GUILD_CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.GUILD_CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: management-api
