name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        check:
          - format
    name: Check ${{ matrix.check }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        run: pnpm install

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Check
        run: pnpm check:${{ matrix.check }}

  # Build all packages and applications, and creates Docker images
  build-latest:
    name: build
    needs: [check]
    uses: ./.github/workflows/build-and-dockerize.yaml
    # Only run for `main` branch
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    with:
      imageTag: ${{ github.sha }}
      publishLatest: true
      targets: "build"
      publishPrComment: false
    secrets: inherit

  # Deploy to preview environment
  deploy-preview:
    name: deploy
    needs: [build-latest]
    uses: ./.github/workflows/deploy.yaml
    concurrency:
      group: "deploy-dev"
    # Only run for `main` branch
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    with:
      ref: ${{ github.sha }}
      environment: "theguild/dev"
    secrets: inherit
