name: Deployment
on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
        description: "Docker Image Tag (commit ID)"
      environment:
        type: string
        required: true
        default: "theguild/dev"

jobs:
  deploy:
    name: Deploy to Pulumi
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ env.COMMIT_ID }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Push to Cluster
        uses: pulumi/actions@v3
        with:
          command: up
          stack-name: ${{ inputs.environment }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          work-dir: deployments
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_TOKEN }}
          DOCKER_IMAGE_TAG: ${{ inputs.ref }}
          PULUMI_K8S_SUPPRESS_HELM_HOOK_WARNINGS: 1
