name: Deployment Manual

on:
  workflow_dispatch:
    inputs:
      ref:
        required: true
        description: "Docker Image Tag (commit ID)"
      environment:
        type: choice
        description: "Environment"
        required: true
        default: "theguild/dev"
        options:
          - "theguild/dev"
          # Only support preview env at the moment in cluster.
          # - staging
          # - production

run-name: 'Deploy "${{ inputs.ref }}" (by ${{ github.actor }})'
concurrency:
  group: "deploy-${{ inputs.environment }}"

jobs:
  rollout:
    name: Rollout to cluster
    uses: "./.github/workflows/deploy.yaml"
    with:
      ref: ${{ inputs.ref }}
      environment: ${{ inputs.environment }}
    secrets: inherit
